version: '2'

services:
    app:
        container_name: app
        build: .docker/php
        volumes:
            - .:/app
            - ./var/logs:/app/var/logs
            - ./var/cache.:/app/var/cache

    nginx:
        container_name: sf.nginx
        build: .docker/nginx
        volumes_from:
            - app
        ports:
            - "81:80"

    wiremock:
        container_name: test-wiremock
        image: rodolpheche/wiremock
        volumes:
            - ./app/wiremock:/home/wiremock
        expose:
            - 80
        ports:
            - "8089:80"
        command:
            - "java"
            - "-cp"
            - "/var/wiremock/lib/*:/var/wiremock/extensions/*"
            - "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner"
            - "--local-response-templating"
            - "--port"
            - "80"
            - "--verbose"

    db:
        container_name: test-db
        image: percona/percona-server:5.7
        ports: ["3320:3306"]
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: test
            MYSQL_DATABASE: test
            MYSQL_PASSWORD: test
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
