<?php

namespace AppBundle\Repository;

/**
 * PayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayoutRepository extends \Doctrine\ORM\EntityRepository
{
}
